In [3]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils

In [4]:
numpy.random.seed(7)

In [9]:
'''
raw dataset is abcd.. 
'''
dataset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
char_to_int = dict((c,i) for i, c in enumerate(dataset))
int_to_char = dict((i,c) for i, c in enumerate(dataset))

In [29]:
#problem char
sequence_length = 3
dataX = []
dataY = []

In [30]:
for i in range(0, len(dataset)-sequence_length, 1):
    in_seq = dataset[i:i+sequence_length]
    out_seq = dataset[i+sequence_length]
    
    dataX.append([char_to_int[char] for char in in_seq])
    dataY.append(char_to_int[out_seq])
    print(in_seq+"->"+out_seq)

ABC->D
BCD->E
CDE->F
DEF->G
EFG->H
FGH->I
GHI->J
HIJ->K
IJK->L
JKL->M
KLM->N
LMN->O
MNO->P
NOP->Q
OPQ->R
PQR->S
QRS->T
RST->U
STU->V
TUV->W
UVW->X
VWX->Y
WXY->Z


In [45]:
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (len(dataX), sequence_length, 1)) #row,col, ?
print(X)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 1]
  [ 2]
  [ 3]]

 [[ 2]
  [ 3]
  [ 4]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 5]
  [ 6]
  [ 7]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 7]
  [ 8]
  [ 9]]

 [[ 8]
  [ 9]
  [10]]

 [[ 9]
  [10]
  [11]]

 [[10]
  [11]
  [12]]

 [[11]
  [12]
  [13]]

 [[12]
  [13]
  [14]]

 [[13]
  [14]
  [15]]

 [[14]
  [15]
  [16]]

 [[15]
  [16]
  [17]]

 [[16]
  [17]
  [18]]

 [[17]
  [18]
  [19]]

 [[18]
  [19]
  [20]]

 [[19]
  [20]
  [21]]

 [[20]
  [21]
  [22]]

 [[21]
  [22]
  [23]]

 [[22]
  [23]
  [24]]]


In [46]:
# normalize
X = X / float(len(dataset))
print(X)
# one hot encode the output variable
y = np_utils.to_categorical(dataY)
print(y)

[[[0.        ]
  [0.03846154]
  [0.07692308]]

 [[0.03846154]
  [0.07692308]
  [0.11538462]]

 [[0.07692308]
  [0.11538462]
  [0.15384615]]

 [[0.11538462]
  [0.15384615]
  [0.19230769]]

 [[0.15384615]
  [0.19230769]
  [0.23076923]]

 [[0.19230769]
  [0.23076923]
  [0.26923077]]

 [[0.23076923]
  [0.26923077]
  [0.30769231]]

 [[0.26923077]
  [0.30769231]
  [0.34615385]]

 [[0.30769231]
  [0.34615385]
  [0.38461538]]

 [[0.34615385]
  [0.38461538]
  [0.42307692]]

 [[0.38461538]
  [0.42307692]
  [0.46153846]]

 [[0.42307692]
  [0.46153846]
  [0.5       ]]

 [[0.46153846]
  [0.5       ]
  [0.53846154]]

 [[0.5       ]
  [0.53846154]
  [0.57692308]]

 [[0.53846154]
  [0.57692308]
  [0.61538462]]

 [[0.57692308]
  [0.61538462]
  [0.65384615]]

 [[0.61538462]
  [0.65384615]
  [0.69230769]]

 [[0.65384615]
  [0.69230769]
  [0.73076923]]

 [[0.69230769]
  [0.73076923]
  [0.76923077]]

 [[0.73076923]
  [0.76923077]
  [0.80769231]]

 [[0.76923077]
  [0.80769231]
  [0.84615385]]

 [[0.80769231

In [47]:
# create and fit the model
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [48]:
model.fit(X, y, epochs=500, batch_size=1, verbose=2)

Epoch 1/500
 - 1s - loss: 3.2752 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 3.2617 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 3.2530 - acc: 0.0000e+00
Epoch 4/500
 - 0s - loss: 3.2461 - acc: 0.0000e+00
Epoch 5/500
 - 0s - loss: 3.2396 - acc: 0.0000e+00
Epoch 6/500
 - 0s - loss: 3.2324 - acc: 0.0435
Epoch 7/500
 - 0s - loss: 3.2252 - acc: 0.0435
Epoch 8/500
 - 0s - loss: 3.2172 - acc: 0.0435
Epoch 9/500
 - 0s - loss: 3.2084 - acc: 0.0435
Epoch 10/500
 - 0s - loss: 3.2000 - acc: 0.0435
Epoch 11/500
 - 0s - loss: 3.1886 - acc: 0.0435
Epoch 12/500
 - 0s - loss: 3.1755 - acc: 0.0435
Epoch 13/500
 - 0s - loss: 3.1638 - acc: 0.0435
Epoch 14/500
 - 0s - loss: 3.1476 - acc: 0.0435
Epoch 15/500
 - 0s - loss: 3.1305 - acc: 0.0435
Epoch 16/500
 - 0s - loss: 3.1096 - acc: 0.0435
Epoch 17/500
 - 0s - loss: 3.0892 - acc: 0.0435
Epoch 18/500
 - 0s - loss: 3.0747 - acc: 0.0435
Epoch 19/500
 - 0s - loss: 3.0496 - acc: 0.0435
Epoch 20/500
 - 0s - loss: 3.0255 - acc: 0.0435
Epoch 21/500
 - 0s - loss: 3.

Epoch 170/500
 - 0s - loss: 1.1015 - acc: 0.7826
Epoch 171/500
 - 0s - loss: 1.0925 - acc: 0.7826
Epoch 172/500
 - 0s - loss: 1.0964 - acc: 0.8261
Epoch 173/500
 - 0s - loss: 1.0825 - acc: 0.8696
Epoch 174/500
 - 0s - loss: 1.0814 - acc: 0.8696
Epoch 175/500
 - 0s - loss: 1.0805 - acc: 0.8261
Epoch 176/500
 - 0s - loss: 1.0736 - acc: 0.8696
Epoch 177/500
 - 0s - loss: 1.0758 - acc: 0.8261
Epoch 178/500
 - 0s - loss: 1.0721 - acc: 0.8261
Epoch 179/500
 - 0s - loss: 1.0608 - acc: 0.8261
Epoch 180/500
 - 0s - loss: 1.0516 - acc: 0.8696
Epoch 181/500
 - 0s - loss: 1.0547 - acc: 0.7826
Epoch 182/500
 - 0s - loss: 1.0455 - acc: 0.8261
Epoch 183/500
 - 0s - loss: 1.0475 - acc: 0.8696
Epoch 184/500
 - 0s - loss: 1.0386 - acc: 0.8696
Epoch 185/500
 - 0s - loss: 1.0318 - acc: 0.9130
Epoch 186/500
 - 0s - loss: 1.0258 - acc: 0.8696
Epoch 187/500
 - 0s - loss: 1.0292 - acc: 0.9130
Epoch 188/500
 - 0s - loss: 1.0155 - acc: 0.8696
Epoch 189/500
 - 0s - loss: 1.0141 - acc: 0.8261
Epoch 190/500
 - 0s 

 - 0s - loss: 0.5163 - acc: 0.9565
Epoch 338/500
 - 0s - loss: 0.5112 - acc: 0.9565
Epoch 339/500
 - 0s - loss: 0.5142 - acc: 0.9565
Epoch 340/500
 - 0s - loss: 0.5104 - acc: 0.9565
Epoch 341/500
 - 0s - loss: 0.5036 - acc: 0.9565
Epoch 342/500
 - 0s - loss: 0.5075 - acc: 0.9130
Epoch 343/500
 - 0s - loss: 0.5024 - acc: 0.9565
Epoch 344/500
 - 0s - loss: 0.5011 - acc: 0.9565
Epoch 345/500
 - 0s - loss: 0.5012 - acc: 0.9130
Epoch 346/500
 - 0s - loss: 0.4948 - acc: 0.9565
Epoch 347/500
 - 0s - loss: 0.4940 - acc: 0.9565
Epoch 348/500
 - 0s - loss: 0.5074 - acc: 0.9130
Epoch 349/500
 - 0s - loss: 0.4985 - acc: 0.9565
Epoch 350/500
 - 0s - loss: 0.4883 - acc: 0.9565
Epoch 351/500
 - 0s - loss: 0.4812 - acc: 0.9565
Epoch 352/500
 - 0s - loss: 0.4886 - acc: 0.9565
Epoch 353/500
 - 0s - loss: 0.4826 - acc: 0.9565
Epoch 354/500
 - 0s - loss: 0.4890 - acc: 0.9565
Epoch 355/500
 - 0s - loss: 0.4853 - acc: 0.9565
Epoch 356/500
 - 0s - loss: 0.4912 - acc: 1.0000
Epoch 357/500
 - 0s - loss: 0.4968

In [49]:
# summarize performance of the model
scores = model.evaluate(X, y, verbose=0)
print("Model Accuracy: %.2f%%" % (scores[1]*100))

Model Accuracy: 100.00%


In [50]:
for pattern in dataX:
    x = numpy.reshape(pattern, (1, len(pattern), 1))
    x = x / float(len(dataset))
    print("x is " + str(x))
    prediction = model.predict(x, verbose=0)
    index = numpy.argmax(prediction)
    print("prediction is " + str(prediction))
    print("index is " + str(index))
    result = int_to_char[index]
    seq_in = [int_to_char[value] for value in pattern]
    print(seq_in, "->", result)

x is [[[0.        ]
  [0.03846154]
  [0.07692308]]]
prediction is [[3.0294918e-06 2.6933681e-06 2.7942276e-06 9.7982478e-01 1.7722700e-02
  8.6215738e-04 1.4631011e-04 7.2069161e-05 1.2738420e-05 1.0896248e-05
  3.4931327e-05 2.6606492e-06 4.4723416e-07 1.9707695e-06 2.0078531e-07
  5.0251145e-07 6.2481092e-07 8.1065861e-07 1.6348587e-06 1.9067599e-07
  1.3395839e-07 1.0081470e-06 4.4102430e-06 2.0901550e-06 2.7853957e-05
  1.2603247e-03]]
index is 3
['A', 'B', 'C'] -> D
x is [[[0.03846154]
  [0.07692308]
  [0.11538462]]]
prediction is [[1.7493734e-06 1.2188567e-06 1.6963984e-06 9.7193643e-03 9.6312094e-01
  2.3613650e-02 1.5148362e-03 1.4543904e-03 1.6686194e-04 7.1804556e-05
  3.7676124e-05 8.8712250e-06 1.6666535e-06 1.5827372e-05 1.0407841e-06
  2.3638511e-07 2.2884633e-07 7.0752770e-07 1.5688192e-06 1.3750677e-07
  8.9604434e-08 4.6409735e-07 2.3091995e-06 2.0798875e-07 7.7031254e-06
  2.5474193e-04]]
index is 4
['B', 'C', 'D'] -> E
x is [[[0.07692308]
  [0.11538462]
  [0.15384615